[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bargaineer"
version = "0.1.0"
dependencies = [
	"pyjwt",
	"python-dotenv",
	"pytz",
	"requests",
	"sqlalchemy",
	"tqdm",
]

[tool.setuptools]
packages = ["bargaineer"]
